### ISSUE TITLE
Author Attribution

### ISSUE THREAD

**Issue by egmulky** [SoftwareEngineeringToolDemos/ICSE-2013-Refoqus#3]
The readme can be improved by mentioning all the authors who worked on the original paper for the tool

**Comment by egmulky** [comment]
fixed by egmulky

**Comment by YashwanthAsh** [comment]
As per the rubric "Does the readme thank any original authors who provided help?" instruction we have to thank(give attribution) to the author who responded and helped to our emails.

**Comment by egmulky** [comment]
This was a suggestion to improve the readme by giving credit to all authors involved in developing the tool.Thanks !
